name: CI
on:
on:
  push:
    branches: [ task6 ]
  pull_request:
    branches: [ task6 ]


jobs:

  Build_with_tests:

    runs-on: ubuntu-latest

    steps:

        - uses: actions/checkout@v2

        - name: Build
        run: cd task6 && mkdir build && cd build && cmake ..
