name: CI
on:
  push:
    branches: [ task6 ]
  pull_request:
    branches: [ task6 ]


jobs:
    Build_with_tests:
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v2

          - name: Build
            run: |
              cd task6
              cd task-ci
              mkdir 3rdparty
              cd 3rdparty
              wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz
              tar xf release-1.8.0.tar.gz
              cd ..
              mkdir build
              cd build
              cmake -DGOOGLE_TEST_DIR=googletest-release-1.8.0 ..
              make
          - name: Test
            uses: akhtyamovpavel/ActionGtestReport@v0.0.9
            with:
             exec-path: task6/task-ci/build/bin/CTestExe
             report-path: report.xml
             working-directory: task6/task-ci
